<a href="https://colab.research.google.com/github/KwonDoRyoung/AdvancedBasicEducationProgram/blob/main/%08abep07.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#   PyTorch 활용하기

---
##▶︎ 오늘 강의내용
*   Pytorch Tensor 이해하기
*   Pytorch 활용하여 Linear regression 구현
*   Pytorch 활용하여 Logistic regression 구현

---
##⦿   Pytorch Tensor 종류 및 특징
- Tensor는 배열 및 행렬과 유사한 데이터 구조
- Pytorch Tensor는 Numpy ndarray와 유사함
- Pytorch Tensor는 미분에 최적화되어 있음
![Alt Text](https://github.com/KwonDoRyoung/AdvancedBasicEducationProgram/blob/main/markdown_images/doc_tensor.png?raw=true)

In [6]:
import torch
import numpy as np

data = [[5, 7], [11, 9]]
n_data = np.array([[5, 7], [11, 9]])
t_data = torch.tensor([[5, 7], [11, 9]])

# 보기 쉽게 하기 위해 다음과 같이 표현함
print(f"* list\n{data}\n")
print(f"* numpy:\n{n_data}\n")
print(f"* tensor:\n{t_data}")

* list
[[5, 7], [11, 9]]

* numpy:
[[ 5  7]
 [11  9]]

* tensor:
tensor([[ 5,  7],
        [11,  9]])


###• Numpy ⇔ Tensor 서로 변환하기

###• 크기가 동일하지만 데이터는 다르게 만드는 Tensor

In [7]:
import torch

t_data = torch.tensor([[5, 7], [11, 9]])

t_ones = torch.ones_like(t_data)
print(f"Ones Tensor:\n {t_ones}\n")

Ones Tensor:
 tensor([[1, 1],
        [1, 1]])



###• Random & Constant 

###• Tensor 의 부가적인 속성

---
##⦿   Pytorch Tensor 연산

###• Slicing & Indexing

###• Slicing & Indexing

###• Concatenate or Stack

###• 행렬 연산

---
##⦿   Linear regression 구현

---
##⦿   Logistic regression 구현